/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoomsListRouteImport } from './routes/rooms-list'
import { Route as CreateRoomRouteImport } from './routes/create-room'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'

const RoomsListRoute = RoomsListRouteImport.update({
  id: '/rooms-list',
  path: '/rooms-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoomRoute = CreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/create-room': typeof CreateRoomRoute
  '/rooms-list': typeof RoomsListRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/create-room': typeof CreateRoomRoute
  '/rooms-list': typeof RoomsListRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/create-room': typeof CreateRoomRoute
  '/rooms-list': typeof RoomsListRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/create-room' | '/rooms-list' | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/create-room' | '/rooms-list' | '/room/$roomId'
  id: '__root__' | '/create-room' | '/rooms-list' | '/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CreateRoomRoute: typeof CreateRoomRoute
  RoomsListRoute: typeof RoomsListRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rooms-list': {
      id: '/rooms-list'
      path: '/rooms-list'
      fullPath: '/rooms-list'
      preLoaderRoute: typeof RoomsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-room': {
      id: '/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof CreateRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CreateRoomRoute: CreateRoomRoute,
  RoomsListRoute: RoomsListRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
